---
permalink: task_active_iq_replication.html 
sidebar: sidebar 
keywords: solidfire, active, iq, replication 
summary: Erfahren Sie mehr über die Replikationsseite in SolidFire Active IQ. 
---
= Replizierung
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die Seite *Replikation*, die im Seitenbereich für einen ausgewählten Cluster verfügbar ist, enthält Informationen zu Cluster-Paaren und Volume-Paaren.

Erfahren Sie mehr über die Seiten zu Cluster-Paaren und Volumes-Paaren:

* <<cluster_pairs,Cluster-Paare>>
* <<volume_pairs,Volume-Paare>>
* <<snapmirror_endpoints,SnapMirror Endpunkte>>
* <<snapmirror_relationships,SnapMirror Beziehungen>>




== Cluster-Paare

Auf der Seite *Replikation* > *Cluster-Paare* für einen ausgewählten Cluster können Sie die folgenden Informationen zu Cluster-Paaren anzeigen.

[cols="30,70"]
|===
| Überschrift | Beschreibung 


| Cluster-Paar-ID | ID-Nummer, die beim Erstellen des Cluster-Paars angegeben wurde. 


| Remote-Cluster-Name | Name des Remote-Clusters des Paars. 


| Remote-MVIP | Management Virtual IP des Remote-Clusters: 


| Replizierung Von Volumes | Gibt die Anzahl der Volumes an, die auf dem gepaarten Cluster repliziert werden. 


| Status | Status des Cluster-Paars. 


| UUID | Universell eindeutige Kennung. 
|===


== Volume-Paare

Auf der Seite *Replikation* > *Volume Pairs* für einen ausgewählten Cluster können Sie die folgenden Informationen zu Volume-Paaren anzeigen.

[cols="30,70"]
|===
| Überschrift | Beschreibung 


| Volume-ID | ID-Nummer, die beim Erstellen des Volumes angegeben wurde. 


| Konto-ID | ID des Kontos, der dem Volume zugewiesen wurde. 


| Volume-Status | Zustand des replizierten Volumes. 


| Replikationsmodus | Für das Volume-Paar ausgewählter Modetyp. 


| Richtung  a| 
Gibt die Richtung der Volume-Daten an:

* Quelle: Gibt an, dass Daten auf ein Ziel außerhalb des Clusters geschrieben werden.
* Ziel: Gibt an, dass von einer externen Quelle Daten auf das lokale Volume geschrieben werden.




| Asynchrone Verzögerung  a| 
Dauer, seit das Volume zuletzt mit dem Remote-Cluster synchronisiert wurde. Wenn das Volume nicht gekoppelt ist, ist dieser Wert Null.


NOTE: Ein Ziel-Volume im aktiven Replikationszustand hat immer eine asynchrone Verzögerung von 0 (Null). Ziel-Volumes erkennen während der Replizierung das System und gehen davon aus, dass die asynchrone Verzögerung zu jeder Zeit korrekt ist.



| Remote-Cluster | Name des Remote-Clusters, auf dem sich das Volume befindet. 


| Remote-Volume-ID | Volume-ID des Volumes im Remote-Cluster. 
|===


== SnapMirror Endpunkte

Auf der Seite *Replication* > *SnapMirror Endpoints* für einen ausgewählten Cluster können Sie die folgenden Informationen zu SnapMirror Endpunkten anzeigen.

[cols="30,70"]
|===
| Überschrift | Beschreibung 


| Endpunkt-ID | Die ID-Nummer des Endpunkts. 


| Remote-Cluster-Name | Name des Remote-Clusters des Paars. 


| Cluster-Management-IP | Cluster-Management-IP-Adresse. 


| IPS | Der Bereich der virtuellen Netzwerk-IP-Adressen, die für das virtuelle Netzwerk verwendet werden. 


| Beziehungen | Die Anzahl der für einen Endpunkt konfigurierten Beziehungen. 


| Status | Dies bezieht sich darauf, ob der Endpunkt derzeit verbunden ist oder nicht. Es hat einen Wert von *connected* oder *disconnected*. 
|===


== SnapMirror Beziehungen

Auf der Seite *Replication* > *SnapMirror Relationships* für einen ausgewählten Cluster können Sie die folgenden Informationen zu SnapMirror Beziehungen anzeigen.

[cols="30,70"]
|===
| Überschrift | Beschreibung 


| Endpunkt-ID | Die ID-Nummer des Endpunkts. 


| Quell-Volume | Die Volume-ID der Quelle. 


| Ziel-Cluster | Der Name des Ziel-Clusters in der SnapMirror-Beziehung. 


| Ziel-Volume | Der Name des Ziel-Volume in der SnapMirror-Beziehung. 


| Bundesland  a| 
Der Zustand der Spiegelbeziehung. Es können drei mögliche Werte sein:

* Nicht initialisiert: Das Ziel-Volume wurde nicht initialisiert.
* Snapmirrored: Das Ziel-Volume wird initialisiert und ist bereit, SnapMirror Updates zu erhalten.
* Abgebrochen: Das Zielvolume befindet sich im Lese-/Schreibzustand und Snapshots sind vorhanden.




| Status  a| 
Wenn die Beziehung derzeit gesund ist, kann sie einen Wert von *gesund* oder *ungesund* haben.


NOTE: Wenn eine manuelle oder geplante Aktualisierung fehlschlägt oder abgebrochen wird oder die letzte geplante Aktualisierung verzögert wird, kann dies zu einem *ungesunden* Wert führen. Das Feld *Details*, das dem Status folgt, zeigt den Grund für den Status *ungesund* an.



| Beziehungstyp  a| 
Die Art der SnapMirror-Beziehung.


NOTE: Auf SolidFire Systemen ist diese Einstellung immer auf festgelegt `extended_data_protection`. NetApp Systeme besitzen andere Arten von gültigen Beziehungen, die bei SolidFire Systemen nicht gelten.



| Bundesland  a| 
Der Status des Clusters:

* Zustand: Mit dem Cluster sind keine kritischen Fehler verbunden.
* Offline: Zugriff auf das Cluster nicht möglich. Wählen Sie den Link aus, um das Fehlerprotokoll anzuzeigen.
* Fehler: Mit diesem Cluster sind Fehler verbunden. Wählen Sie den Link aus, um das Fehlerprotokoll anzuzeigen.




| Details | Informationen, die zum Identifizieren der SnapMirror Beziehung beitragen. 
|===


== Weitere Informationen

* https://www.netapp.com/support-and-training/documentation/["NetApp Produktdokumentation"^]
* https://docs.netapp.com/us-en/ontap/element-replication/index.html["Replizierung zwischen NetApp Element Software und ONTAP"^]

